# Generated by Django 6.0.3 on 2026-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='departure_location',
            field=models.CharField(blank=True, help_text='Starting point of the delivery', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='destination_location',
            field=models.CharField(blank=True, help_text='Final destination of the delivery', max_length=255, null=True),
        ),
    ]
